### PR TITLE
Adjust for YAML screenshot data

### PR DESCRIPTION
**Pull request by gagern**

### CODE REVIEW

**Comment by k4b7** [comment]
@gagern I think I'm going to rebase fonts-p2_rendering so that the pull request stays clean.

**Comment by gagern** [comment]
Sure. Feel free to use the merged version of `ss_data.yaml` if you feel like it, or recreate it yourself if not. `git show bbc9b9f:test/screenshotter/ss_data.yaml > test/screenshotter/ss_data.yaml` might be of use. Or `git reset bbc9b9f -- test/screenshotter/ss_data.yaml`. Or manual copy & paste from [the file content](https://github.com/gagern/KaTeX/blob/bbc9b9f2c08b1981bf03368b9a87f4374d8514b2/test/screenshotter/ss_data.yaml#L68-L77).

**Comment by k4b7** [comment]
> Feel free to use the merged version of ss_data.yaml...

Thanks, I will... and thank you for doing the hard work.  :smile:

**Comment by k4b7** [comment]
Looks like this got merged into Khan/KaTeX a while ago.

**Pull request closed without merging**
